#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  wget -O - https://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
  echo "deb https://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
  sudo apt-get update
  sudo apt-get install elasticsearch
}

bootstrap
