#!/usr/bin/env bash

function _elasticsearch_profile {
  local shome="${_elasticsearch_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
}

_elasticsearch_profile
